# Generated by Django 6.0.1 on 2026-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=' ', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
