# Generated by Django 6.0.1 on 2026-03-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='file',
        ),
    ]
