# Generated by Django 6.0.1 on 2026-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
